version: '3.7'
services: 
  service-one:
    build: ./service-one
    ports: 
    - target: 5000
      published: 5000
      protocol: tcp
  service-two:
    build: ./service-two
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service-three:
    build: ./service-three
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service-four:
    build: ./service-four
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf