- name: "update"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python-pip
    - python3-pip
    update_cache: true
- name: "Install python docker module"
  pip:
    name:
    - docker
    - jsondiff
- name: "Get Keys"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: "Make repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: "Install Docker Engine"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
    state: latest
- name: "Add user to the docker group"
  user:
    name: docker
    shell: /bin/bash
    group: docker
    state: present